package GUI;

import com.intellij.uiDesigner.core.GridConstraints;
import com.intellij.uiDesigner.core.GridLayoutManager;
import com.intellij.uiDesigner.core.Spacer;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;

public class MyApp extends JFrame {
    private JPanel mainPanel;
    private JButton mainButton;

    public MyApp(String appTitle) {
        super(appTitle);

        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        this.pack();
        this.setSize(300, 300);


        JPanel thisMainPanel = new JPanel();
        thisMainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        thisMainPanel.setBackground(new Color(-15253213));
        thisMainPanel.setForeground(new Color(-2599894));
        JButton thisMainButton = new JButton();
        thisMainButton.setBackground(new Color(-2599894));
        thisMainButton.setText("Button");
        thisMainPanel.add(mainButton);


        this.mainButton.addActionListener(new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                JOptionPane.showMessageDialog(null, "You have pressed the button");
            }
        });

        this.mainPanel = thisMainPanel;
        this.mainButton = thisMainButton;

        this.setContentPane(thisMainPanel);

    }


    public static void main(String[] args) {
        JFrame frame = new MyApp("my new app");
        frame.setVisible(true);
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        mainPanel.setBackground(new Color(-15253213));
        mainPanel.setForeground(new Color(-2599894));
        mainButton = new JButton();
        mainButton.setBackground(new Color(-2599894));
        mainButton.setText("Button");
        mainPanel.add(mainButton);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }

}
